2023-07-14 05:13:30,421 INFO    MainThread:59130 [wandb_setup.py:_flush():76] Current SDK version is 0.15.6.dev1
2023-07-14 05:13:30,422 INFO    MainThread:59130 [wandb_setup.py:_flush():76] Configure stats pid to 59130
2023-07-14 05:13:30,422 INFO    MainThread:59130 [wandb_setup.py:_flush():76] Loading settings from /Users/estellaxin/.config/wandb/settings
2023-07-14 05:13:30,422 INFO    MainThread:59130 [wandb_setup.py:_flush():76] Loading settings from /private/var/folders/vh/k98fyx251l792bbzj485tdnw0000gp/T/tmpzlvjzkea/wandb/settings
2023-07-14 05:13:30,422 WARNING MainThread:59130 [wandb_setup.py:_flush():76] Unknown environment variable: WANDB_ERROR_REPORTING
2023-07-14 05:13:30,422 INFO    MainThread:59130 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_network_buffer': '1000', 'username': 'test_run_in_launch_context_with_artifact_unique', 'base_url': 'http://localhost:58825', 'api_key': '***REDACTED***'}
2023-07-14 05:13:30,422 INFO    MainThread:59130 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-14 05:13:30,422 INFO    MainThread:59130 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-14 05:13:30,422 INFO    MainThread:59130 [wandb_init.py:_log_setup():507] Logging user logs to /Users/estellaxin/Projects/wandb/tests/pytest_tests/unit_tests_old/logs/test_run_in_launch_context_with_artifact_unique/wandb/run-20230714_051330-15j2vy7j/logs/debug.log
2023-07-14 05:13:30,422 INFO    MainThread:59130 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/estellaxin/Projects/wandb/tests/pytest_tests/unit_tests_old/logs/test_run_in_launch_context_with_artifact_unique/wandb/run-20230714_051330-15j2vy7j/logs/debug-internal.log
2023-07-14 05:13:30,422 INFO    MainThread:59130 [wandb_init.py:init():547] calling init triggers
2023-07-14 05:13:30,422 INFO    MainThread:59130 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'epochs': 2, 'lr': 0.004}
2023-07-14 05:13:30,422 INFO    MainThread:59130 [wandb_init.py:init():596] starting backend
2023-07-14 05:13:30,422 INFO    MainThread:59130 [wandb_init.py:init():600] setting up manager
2023-07-14 05:13:30,427 INFO    MainThread:59130 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-07-14 05:13:30,429 INFO    MainThread:59130 [wandb_init.py:init():606] backend started and connected
2023-07-14 05:13:30,434 INFO    MainThread:59130 [wandb_run.py:_config_callback():1282] config_cb None None {'epochs': 10}
2023-07-14 05:13:30,450 INFO    MainThread:59130 [wandb_init.py:init():697] updated telemetry
2023-07-14 05:13:30,475 INFO    MainThread:59130 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-07-14 05:13:30,511 INFO    MainThread:59130 [wandb_run.py:_on_init():2174] communicating current version
2023-07-14 05:13:30,805 INFO    MainThread:59130 [wandb_run.py:_on_init():2183] got version response 
2023-07-14 05:13:30,811 INFO    MainThread:59130 [wandb_init.py:init():781] starting run threads in backend
2023-07-14 05:13:30,903 INFO    MainThread:59130 [wandb_run.py:_console_start():2153] atexit reg
2023-07-14 05:13:30,903 INFO    MainThread:59130 [wandb_run.py:_redirect():2008] redirect: off
2023-07-14 05:13:30,905 INFO    MainThread:59130 [wandb_init.py:init():822] run started, returning control to user process
2023-07-14 05:13:33,477 INFO    MainThread:59130 [wandb_run.py:_finish():1888] finishing run mock_server_entity/test/15j2vy7j
2023-07-14 05:13:33,477 INFO    MainThread:59130 [wandb_run.py:_atexit_cleanup():2122] got exitcode: 0
2023-07-14 05:13:33,477 INFO    MainThread:59130 [wandb_run.py:_restore():2105] restore
2023-07-14 05:13:33,477 INFO    MainThread:59130 [wandb_run.py:_restore():2111] restore done
2023-07-14 05:13:34,486 WARNING MsgRouterThr:59130 [router.py:message_loop():77] message_loop has been closed
2023-07-14 05:13:44,508 INFO    MainThread:59130 [wandb_run.py:_restore():2105] restore
2023-07-14 05:13:44,508 INFO    MainThread:59130 [wandb_run.py:_restore():2111] restore done
